### PR TITLE
Apply multiple filters

### PR DESCRIPTION
**Pull request by alonpeer**
In this PR, I've updated the ElasticSearch query to take into account multiple filters (e.g. country "Germany" AND city "Berlin"), and updated the filters UI to enable applying multiple filters. 

I've also refactored `_search_filter.erb`, by parameterizing the filters and making the HTML DRYer, so that it's easier to apply changes to all filters at once.

This PR is built on top of https://github.com/rubymonsters/speakerinnen_liste/pull/1038, so that PR should be merged first.

sp-search-filters

### CODE REVIEW

**Comment by alonpeer** [comment]
@tyranja, since I'm not in the github group of speakerinnen, I cannot open PRs directly on the main repo. Instead I'm opening this from a fork I have of the project. It would be easier if I could open PRs directly on the project.
Meanwhile, I've implemented what we talked about in this PR, which I've opened so you can review it, and once I have access, I'll open the PR again on the main repo.

**Comment by alonpeer** [comment]
This is the first step, and next I'd like to add the "services" filter, and the two "willing to..." filters. I'll do those in a later stage, since I don't know when I'll be available for that.

**Comment by tyranja** [comment]
So cool!!!!

**Comment by alonpeer** [comment]
Closed and re-opened at https://github.com/rubymonsters/speakerinnen_liste/pull/1047

**Pull request closed without merging**
